services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: au
      POSTGRES_PASSWORD: au
      POSTGRES_DB: au_todo
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
